name: chore_pal
description: A Flutter application for managing children's chores
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  integration_test:
    sdk: flutter
  provider: ^6.0.5
  cupertino_icons: ^1.0.2
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  cloud_functions: ^5.0.0
  intl: ^0.20.2
  confetti: ^0.8.0
  flutter_local_notifications: ^17.2.3
  permission_handler: ^11.3.1
  timezone: ^0.9.4
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/chorepal-logo-ideas.png"
  adaptive_icon_background: "#0277BD"
  adaptive_icon_foreground: "assets/images/chorepal-logo-ideas.png"
  windows:
    generate: true
    image_path: "assets/images/chorepal-logo-ideas.png"
    icon_size: 48